name: coffee_api
description: Package to retrieve from the coffee API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.7
  http: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.14
  very_good_analysis: ^7.0.0
