name: local_storage
description: Package to handle saving and loading images locally
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  # TODO: Look for a way to avoid having a dependency on http in this package
  http: ^1.3.0
  path_provider: ^2.1.5

dev_dependencies:
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  test: ^1.25.14
  very_good_analysis: ^7.0.0
